title: Lone Fondness
description: >- # this means to ignore newlines until "baseurl:"
  No accounts. No ads. Just three friends, one fire, and a deck of cards.

remote_theme: pages-themes/cayman@v0.2.0